swagger: "2.0"
info:
  title: Airport Codes
  description: Get the name of an airport from its three-letter IATA code.
  version: 1.0.0
host: YOUR-PROJECT-ID.appspot.com
schemes:
  - "http"
  - "https"
paths:
  /airportName:
    get:
      description: "Get the airport name for a given IATA code."
      operationId: "airportName"
      parameters:
        -
          name: iataCode
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The IATA code is invalid or missing."
